version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: koomodo
      POSTGRES_USER: koomodo_user
      POSTGRES_PASSWORD: koomodo_pass
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: gunicorn koomodo_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: koomodo
      DB_USER: koomodo_user
      DB_PASSWORD: koomodo_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:
